@isTest
public with sharing class CCP_CommonConstantsTest {
    @IsTest
    static void noamalTest(){
        String a = CCP_CommonConstants.UNISSUED;
        String b = CCP_CommonConstants.ISSUED;
        String c = CCP_CommonConstants.REISSUED;
        String d = CCP_CommonConstants.MAILED;
        String e = CCP_CommonConstants.REISSUEDDONE;
        String f = CCP_CommonConstants.PUBLISH;
        String g = CCP_CommonConstants.REPUBLISH;
        String h = CCP_CommonConstants.RECEIPTCOMPLETED;
        String i = CCP_CommonConstants.CPCASEID;
        String j = CCP_CommonConstants.NEWSID;
        String k = CCP_CommonConstants.NEWSCONTENT;
        String l = CCP_CommonConstants.NEWSURLCONTENT;
        String m = CCP_CommonConstants.MONTHLYAPPLYCASE;
        String n = CCP_CommonConstants.CUSTOMERPORTAL;
        String o = CCP_CommonConstants.MONTHLYAPPLYCASEDESCRIPTION;
        String pa = CCP_CommonConstants.DAY;
        String qa = CCP_CommonConstants.YEAR;
        String ra = CCP_CommonConstants.MONTH;
        String da = CCP_CommonConstants.MONTHEND;
        String ta = CCP_CommonConstants.FILEMONTHEND;
        String ua = CCP_CommonConstants.FINISH;
        Id va = CCP_CommonConstants.FUSOCOMMUNITYPROFILEID;
        Id wa = CCP_CommonConstants.FUSOGROUPID;
        Id xa = CCP_CommonConstants.OPERATIONID;
        Id ya = CCP_CommonConstants.DIRECTBOOKINGID;
        Id za = CCP_CommonConstants.EINVOICEID;
        Id wwa = CCP_CommonConstants.MANAGERID;
        String aaa = CCP_CommonConstants.COMMUNITYALT;
        String ccca = CCP_CommonConstants.CLOSED;
        String vva = CCP_CommonConstants.MAILDONE;
        String bba = CCP_CommonConstants.CATEGORY5;
        String ffa = CCP_CommonConstants.FUSOKNOWLEDGECATEGORY;
        String rra = CCP_CommonConstants.PUBLISHWAITING;
        String eea = CCP_CommonConstants.NOTAPPROVAL;
    }
}